{
 "title": "Data Pipeline Run History & Audit Log Purpose",
 "description": "This dashboard focuses on the execution performance of individual dbt models. It helps you identify long-running models, spot trends in execution time over time, and optimize slow segments of your pipeline. Best for engineers and performance tuning.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Run Success Rate Over Time",
   "type": "barchart",
   "description": "% of successful models per DAG run",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  status,\n  COUNT(*) AS count\nFROM dbt_run_log\nGROUP BY status\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "Execution Time Trends per Model",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  run_started_at,\n  model_id,\n  execution_time\nFROM dbt_run_log\nWHERE run_started_at > NOW() - INTERVAL '7 days'\nORDER BY run_started_at;\n"
    }
   ]
  },
  {
   "title": "Failed Models – Last 24 Hours",
   "type": "logs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  run_started_at,\n  model_id,\n  status,\n  execution_time,\n  thread_id,\n  compiled_sql\nFROM dbt_run_log\nWHERE status = 'fail'\n  AND run_started_at > NOW() - INTERVAL '2 day'\nORDER BY run_started_at DESC;\n"
    }
   ]
  }
 ]
}